src/Area4/ContableBundle/Entity/Producto.php
<?php

namespace Area4\ContableBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Area4\ContableBundle\Entity\Producto
 *
 * @ORM\Table(name="contable_Producto")
 * @ORM\Entity(repositoryClass="Area4\ContableBundle\Entity\ProductoRepository")
 */
class Producto
{
    /** 
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string $codigo 
     * @ORM\Column(name="codigo", type="string")
     */
    private $codigo;

    /**
     * @var float $precio
     *
     * @ORM\Column(name="precio", type="float")
     */
    private $precio;

    /**
     * 
     * @ORM\ManyToOne(targetEntity="EspecificaciondeProducto", inversedBy="producto")
     * @ORM\JoinColumn(name="EspProd_id", referencedColumnName="id")
     *
     * @var Especificacion de Producto
     **/
    private $especificaciondeProducto;
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set precio
     *
     * @param float $precio
     */
    public function setPrecio($precio)
    {
        $this->precio = $precio;
    }

    /**
     * Get precio
     *
     * @return float 
     */
    public function getPrecio()
    {
        return $this->precio;
    }

    /**
     *
     * @param integer $cant
     * @return double 
     */
    public function precioXCant($cant){
        return $this->precio * $cant;
    }

    /**
     * Set codigo
     *
     * @param string $codigo
     */
    public function setCodigo($codigo)
    {
        $this->codigo = $codigo;
    }

    /**
     * Get codigo
     *
     * @return string 
     */
    public function getCodigo()
    {
        return $this->codigo;
    }

    /**
     * Set especificaciondeProducto
     *
     * @param Area4\ContableBundle\Entity\EspecificaciondeProducto $especificaciondeProducto
     */
    public function setEspecificaciondeProducto(\Area4\ContableBundle\Entity\EspecificaciondeProducto $especificaciondeProducto)
    {
        $this->especificaciondeProducto = $especificaciondeProducto;
    }

    /**
     * Get especificaciondeProducto 
     *
     * @return Area4\ContableBundle\Entity\EspecificaciondeProducto 
     */
    public function getEspecificaciondeProducto()
    {
        return $this->especificaciondeProducto;
    }

    /**
     * __toString
     *
     * @return string
     * @author ezekiel
     **/
    public function __toString()
    {
        return (string) $this->especificaciondeProducto->getNombre();
    }

    /**
     * get Nombre
     *
     * @return string
     * @author ezekiel
     **/
    public function getNombre()
    {
        return (string) $this->especificaciondeProducto->__toString();
    }
}

src/Area4/ContableBundle/Form/DocumentoType.php
<?php

namespace Area4\ContableBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;

class DocumentoType extends AbstractType {

	public function buildForm(FormBuilder $builder, array $options) {
		$builder
                    ->add('tipo')
//                    ->add('numero','text')
                    ->add('fecha')
//                    ->add('Responsable')
//                    ->add('created_at')
//                    ->add('update_at')
//                    ->add('total')
//                    ->add('estado')
//		    ->add('created_by')
//		    ->add('update_by')
		;
	}

	public function getName() {
		return 'area4_contablebundle_documentotype';
	}

}

src/Area4/ContableBundle/Controller/DocumentoController.php
<?php

namespace Area4\ContableBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Area4\ContableBundle\Entity\Documento;
use Area4\ContableBundle\Form\DocumentoType;
use Symfony\Component\HttpFoundation\Response;

/**
 * Documento controller.
 *
 * @Route("/documento")
 */
class DocumentoController extends Controller {

	/**
	 * Lists all Documento entities.
	 *
	 * @Route("/", name="documento")
	 * @Template()
	 */
	public function indexAction() {
		return array();
	}
	/**
	 * Lists all Documento entities.
	 *
	 * @Route("/tableIndex", name="documento_table_index")
	 * @Template()
	 */
	public function tableIndexAction() {
		$em = $this->getDoctrine()->getEntityManager();

		$entities = $em->getRepository('Area4ContableBundle:Documento')->findAll();

		return array('entities' => $entities);
	}

	/**
	 * Finds and displays a Documento entity.
	 *
	 * @Route("/{id}/show", name="documento_show")
	 * @Template()
	 */
	public function showAction($id) {
		$em = $this->getDoctrine()->getEntityManager();

		$entity = $em->getRepository('Area4ContableBundle:Documento')->find($id);

		if (!$entity) {
			throw $this->createNotFoundException('Unable to find Documento entity.');
		}

		$deleteForm = $this->createDeleteForm($id);

		return array(
				'entity' => $entity,
				'delete_form' => $deleteForm->createView(),);
	}

	/**
	 * Displays a form to create a new Documento entity.
	 *
	 * @Route("/new", name="documento_new")
	 * @Template()
	 */
	public function newAction() {
		$documento = new Documento();
		$em = $this->getDoctrine()->getEntityManager();
		$tipo = $em->getRepository('Area4ContableBundle:Tipo')->findAll();
		if (!$tipo) {
			throw $this->createNotFoundException('No hay Tipos de Documentos creados. Por favor cree uno');
		}
		$form = $this->createForm(new DocumentoType(), $documento);
		return array(
				'entity' => $documento,
				'form' => $form->createView()
		);
	}

	/**
	 * Creates a new Documento entity.
	 *
	 * @Route("/create", name="documento_create")
	 * @Method("post")
	 * @Template("Area4ContableBundle:Documento:new.html.twig")
	 */
	public function createAction() {
		$documento = new Documento();
		$request = $this->getRequest();
		$form = $this->createForm(new DocumentoType(), $documento);
		$form->bindRequest($request); //Tengo los datos del form

		if ($form->isValid()) {
			$documento->setNumeroAuto();
			$tipo = $documento->getTipo();
			$tipo->plusOneToUltimo();
			$em = $this->getDoctrine()->getEntityManager();
			$em->persist($documento);
			$em->persist($tipo);
			$em->flush();

			return $this->redirect($this->generateUrl('documento_edit',array('id'=>$documento->getId())));
		}

		return array(
				'entity' => $documento,
				'form' => $form->createView()
		);
	}

	/**
	 * Displays a form to edit an existing Documento entity.
	 *
	 * @Route("/{id}/edit", name="documento_edit")
	 * @Template()
	 */
	public function editAction($id) {
		$em = $this->getDoctrine()->getEntityManager();

		$documento = $em->getRepository('Area4ContableBundle:Documento')->find($id);

		if (!$documento) {
			throw $this->createNotFoundException('Unable to find Documento entity.');
		}

		$editForm = $this->createForm(new DocumentoType(), $documento);
		$deleteForm = $this->createDeleteForm($id);

		return array(
				'entity' => $documento,
				'edit_form' => $editForm->createView(),
				'delete_form' => $deleteForm->createView(),
		);
	}

	/**
	 * Edits an existing Documento entity.
	 *
	 * @Route("/{id}/update", name="documento_update")
	 * @ Method("post")
	 * @Template("Area4ContableBundle:Documento:edit.html.twig")
	 */
	public function updateAction($id) {
		$em = $this->getDoctrine()->getEntityManager();

		$entity = $em->getRepository('Area4ContableBundle:Documento')->find($id);
		$request = $this->getRequest();
		$username = $request->request->get('Cliente');
		$Cliente = $em->getRepository('Area4ContableBundle:Cliente')->buscarPorUsername($username);

		if (!$entity) throw $this->createNotFoundException('No se encontro el Documento buscado.');
		if (!$Cliente) throw $this->createNotFoundException('No se encontro el Cliente buscado.');
		
		$entity->setCliente($Cliente);
		$entity->calcularTotal();
		$em->persist($entity);
		$em->flush();

		return new Response();
	}

	/**
	 * Deletes a Documento entity.
	 *
	 * @Route("/{id}/delete", name="documento_delete")
	 * Method("post")
	 */
	public function deleteAction($id) {
			$em = $this->getDoctrine()->getEntityManager();
			$entity = $em->getRepository('Area4ContableBundle:Documento')->find($id);

			if (!$entity) {
				throw $this->createNotFoundException('Unable to find Documento entity.');
			}
			$em->remove($entity);
			$em->flush();
	

		return $this->redirect($this->generateUrl('documento'));
	}

	private function createDeleteForm($id) {
		return $this->createFormBuilder(array('id' => $id))
										->add('id', 'hidden')
										->getForm()
		;
	}

	/**
	 * Lists all Documento entities.
	 *
	 * @Route("/buscar", name="documento_buscar")
	 * @Template("Area4ContableBundle:Documento:index.html.twig")
	 */
	public function buscarAction() {
		$em = $this->getDoctrine()->getEntityManager();
		$q = $this->getRequest()->get('q');
		$Rq = $em->getRepository('Area4ContableBundle:Documento');
		/* @var $Rq \Area4\ContableBundle\Entity\DocumentoRepository */
		if (trim($q) > "") {
			$entities = $Rq->buscar($q);
		} else {
			$entities = $em->getRepository('Area4ContableBundle:Documento')->findAll();
		}
		return array('entities' => $entities);
	}

}

src/Area4/ContableBundle/Resources/views/Documento/edit.html.twig
{% include 'Area4ContableBundle:Documento:facturaEsqueleto.html.twig' %}

{#
<h1>Documento edit</h1>

<form action="{{ path('documento_update', { 'id': entity.id }) }}" method="post" {{ form_enctype(edit_form) }}>
    {{ form_widget(edit_form) }}
    <p>
        <button type="submit">Edit</button>
    </p>
</form>

<ul class="record_actions">
    <li>
        <a href="{{ path('documento') }}">
            Back to the list
        </a>
    </li>
    <li>
        <form action="{{ path('documento_delete', { 'id': entity.id }) }}" method="post">
            {{ form_widget(delete_form) }}
            <button type="submit">Delete</button>
        </form>
    </li>
</ul>
#}

src/Area4/ContableBundle/Resources/views/Documento/facturaEsqueleto.html.twig
<div id="factura">
	<div id="Cabecera">
		<div id="logo">
			<img src="{{asset('img/ideas_competencias_logo_factura.png')}}"/>
		</div>
		<div id="info">
			<b>{{ entity.tipo.nombre | upper }} {{ entity.tipo.letra }}</b><br>
			{{ entity.numero }} <br>
			{{ entity.fecha | date('d | m | Y')}} <br>
			<b>CUIT:</b> <br>
			<b>INGRESOS BRUTOS:</b> <br>
			<b>INICIO ACTIVIDADES:</b> <br>
		</div>
	</div>
	<div id="RazonSocial">
		<label for="Cliente" id="labelCliente">Cliente</label><br>
		<input id="Cliente" type="text" value="{{entity.Cliente}}"/><br>
		<label for="Domicilio" id="labelDomicilio">Domicilio</label><br>
		<input id="Domicilio" type="text" value="Domicilio"/>
	</div>
	<div id="Cuerpo">
		<table class="general" id="lineasdeProducto">
			<tr>
				<th>Cantidad</th>
				<th>Detalle</th>
				<th>Precio Unitario</th>
				<th>Totales</th>
				<th class="ocultar">Accion</th>
			</tr>
		</table>
		<div id="boton"><a href="javascript:agregarCuota()" class="button">Agregar Cuota</a></div>
	</div>
	<div id="footer-factura">
		<p>TOTAL: $<span id="total">0</span></p>
	</div>
	<div id="boton">
		<br>
		<a href="javascript:guardarDocumento();" class="button">Guardar</a>
		<a href="javascript:imprimirFactura();" class="button">Imprimir</a>
	</div><br>
</div>

<script type="text/javascript">
var rowId = 1;
var total = 0;
listLineadeDocumento();
$("a.button").button();

$(function() {
		var Clientes = {% render 'Area4UsuarioBundle:Default:indexAutoCompleteAll'%};
		$( "#Cliente" ).autocomplete({
			source: Clientes
		});
	});

function agregarCuota () {
    setAjaxLoader('#aux');
    var request = $.ajax({
                    type: "POST",
                    url: "{{ path('producto_select')}}"
                });
    request.done(
        function( html ) {
            $("#aux").html(html);
        });
    var dialog = new Dialog();
    dialog.title = "Seleccionar Cuota";
    $('#aux').dialog(dialog);
    abrirDialogo('#aux');
}
function seleccionarCuota(id,nombre,precio){
    $('#aux').dialog('close');
    var request = $.ajax({
        type: "POST",
        url: "{{ path('lineadedocumento_new', {'idDocumento':entity.id}) }}",
        data: "idProducto="+id,
    });
    request.done(function (id) {
        console.log('Linea de Documento[Agregada]');
        agregarLinea(id,nombre,precio);
    });
}

function agregarLinea (id,nombre,precio) {
    $('#dialog #lineasdeProducto').append(
        '<tr id="row'+rowId+'">' +
            '<td class="center">1</td>' +
            '<td class="left">'+nombre+'</td>' +
            '<td class="center">$'+precio+'</td>' +
            '<td class="center">'+precio+'</td>' +
            '<td class="center ocultar">'+
                '<a href="javascript:quitarLinea('+id+','+precio+','+rowId+')" class="button">X</a>' +
            '</td>' +
        '</tr>'
        );
    rowId = rowId + 1;
    sumarPrecio(precio);
}

function quitarLinea (id,precio,rowId) {
    var request = $.ajax({
        type: "POST",
        url: "{{ path('lineadedocumento_remove', {'idDocumento':entity.id}) }}",
        data: "idLineadeDocumento="+id,
    });
    request.done(function () {
        console.log('Linea de Documento[QUITADA]');
        $('#dialog #row'+rowId).remove();
        quitarPrecio(precio);
    });
}

function sumarPrecio (precio) {
    total = total + precio;
    $('#dialog #total').html(total);
}

function quitarPrecio (precio) {
    total = total - precio;
    $('#dialog #total').html(total);
}
function listLineadeDocumento () {
    var request = $.ajax({
        type: "POST",
        url: "{{ path('lineadedocumento_list', {'idDocumento':entity.id}) }}",
    });
    request.done(function (html) {
        $('#dialog #lineasdeProducto').append(html);
    });
}
function imprimirFactura () {
	    var div, imp;

            div = document.getElementById('dialog');//seleccionamos el objeto

            imp = window.open(" ","Formato de Impresion"); //damos un titulo

            imp.document.open();     //abrimos

            imp.document.write('<link rel="stylesheet" type="text/css" href="{{asset('css/iyc.css')}}">'); //tambien podriamos agregarle un <link ...

            imp.document.write(div.innerHTML);//agregamos el objeto

            imp.document.close();

            imp.print();   //Abrimos la opcion de imprimir

            imp.close(); //cerramos la ventana nueva
}

function guardarDocumento () {
	var cliente = $('#Cliente').val();
	var domicilio = $('#Domicilio').val();
	var request = $.ajax({
        type: "POST",
        data: 'Cliente='+cliente+'&Domicilio='+domicilio,
        url: "{{ path('documento_update', {'id':entity.id}) }}",
    });
    request.done(function (html) {
        reloadIndex();
        cerrarDialogo('#dialog');
    });
}
</script>

src/Area4/ContableBundle/Resources/views/Documento/index.html.twig
{%  extends  '::base_backend.html.twig' %}
{%block seccion %}Lista de Documentos{%endblock%}
{% block body %}

<a href="javascript:newDocumento()" class="button-ui-plusthick">Nuevo Documento</a>
<a href="javascript:indexTipoDocumento()" class="button">Tipos de Documento</a>
<a href="javascript:indexEspecificaciondeProducto()" class="button">Especificacion de Cuotas</a>
<a href="javascript:indexProducto()" class="button">Cuotas</a>
<a href="" class="button">Volver</a>
<br/><br/>

<div id="index-documento">
</div>

{% endblock %}
{% block javascripts %}
<script type="text/javascript">
cargarBotones();
reloadIndex();
function newTipoDocumento () {
    setAjaxLoader('#dialog');
    var request = $.ajax({
                    type: "POST",
                    url: "{{ path('tipo_new')}}"
                });
    request.done(
        function( html ) {
            $("#dialog").html(html);
        })
    
    var dialog = new Dialog();
    dialog.title = "Crear un Tipo de Documento";
    $('#dialog').dialog(dialog);
    dialog.aumentar();
    abrirDialogo('#dialog');
}
function indexTipoDocumento() {
    setAjaxLoader('#dialog');
    url = "{{ path('tipo')}}";
    var request = $.ajax({
                    type: "POST",
                    url: url
                });
    request.done(
        function( html ) {
            $("#dialog").html(html);
        })
    
    var dialog = new Dialog();
    dialog.title = "Lista de Tipos de Documento";
    dialog.aumentar();
    $('#dialog').dialog(dialog);
    abrirDialogo('#dialog');
}
function newDocumento () {
    setAjaxLoader('#dialog');
    var request = $.ajax({
                    type: "POST",
                    url: "{{ path('documento_new')}}"
                });
    request.done(
        function( html ) {
            $("#dialog").html(html);
        });
    var dialog = new Dialog();
    dialog.title = "Crear un documento";
    $('#dialog').dialog(dialog);
    abrirDialogo('#dialog');
}
function reloadIndex () {
    setAjaxLoader('#index-documento');
    var request = $.ajax({
        type:"GET",
        url:"{{path('documento_table_index')}}",
    });

    request.done(function (html) {
        $('#index-documento').html(html);
    });
}
function indexProducto () {
    setAjaxLoader('#dialog');
    var request = $.ajax({
                    type: "POST",
                    url: "{{ path('producto')}}"
                });
    request.done(
        function( html ) {
            $("#dialog").html(html);
        });
    var dialog = new Dialog();
    dialog.title = "Lista de Cuotas";
    dialog.aumentar();
    $('#dialog').dialog(dialog);
    abrirDialogo('#dialog');
}
function indexEspecificaciondeProducto () {
    setAjaxLoader('#dialog');
    var request = $.ajax({
                    type: "POST",
                    url: "{{ path('especificaciondeproducto')}}"
                });
    request.done(
        function( html ) {
            $("#dialog").html(html);
        });
    var dialog = new Dialog();
    dialog.title = "Lista de Especificaciones de Cuotas";
    dialog.aumentar();
    dialog.aumentarHorizontal();
    $('#dialog').dialog(dialog);
    abrirDialogo('#dialog');
}
function editDocumento (url) {
    setAjaxLoader('#dialog');
    var request = $.ajax({
                    type: "POST",
                    url: url
                });
    request.done(
        function( html ) {
            $("#dialog").html(html);
        });
    var dialog = new Dialog();
    dialog.aumentar();
    dialog.aumentarHorizontal();
    dialog.aumentarHorizontal();
    dialog.title = "Editar Documento";
    $('#dialog').dialog(dialog);
    abrirDialogo('#dialog');
}

/* ================================================ 

            MODIFICACION DE LA FACTURA 


 ================================================
 */


</script>
{% endblock %}

src/Area4/ContableBundle/Resources/views/Documento/new.html.twig
{% spaceless %}
<form id="formCreate" method="post" {{ form_enctype(form) }}>
    	{{ form_widget(form) }}
    	<br>
    	<a href="javascript:submitForm('#dialog','#formCreate','{{ path('documento_create') }}'); javascript:reloadIndex();" class="button">Crear</a>
</form>
{% endspaceless %}

<script type="text/javascript">
cargarBotonesDialog('#dialog');
</script>
        

src/Area4/ContableBundle/Resources/views/Documento/show.html.twig
<h1>Documento</h1>

<table class="record_properties">
    <tbody>
        <tr>
            <th>Id</th>
            <td>{{ entity.id }}</td>
        </tr>
        <tr>
            <th>Numero</th>
            <td>{{ entity.numero }}</td>
        </tr>
        <tr>
            <th>Fecha</th>
            <td>{{ entity.fecha|date('Y-m-d H:i:s') }}</td>
        </tr>
        <tr>
            <th>Created_at</th>
            <td>{{ entity.createdat|date('Y-m-d H:i:s') }}</td>
        </tr>
        <tr>
            <th>Update_at</th>
            <td>{{ entity.updateat|date('Y-m-d H:i:s') }}</td>
        </tr>
        <tr>
            <th>Total</th>
            <td>{{ entity.total }}</td>
        </tr>
        <tr>
            <th>Estado</th>
            <td>{{ entity.estado }}</td>
        </tr>
    </tbody>
</table>

<ul class="record_actions">
    <li>
        <a href="{{ path('documento') }}">
            Back to the list
        </a>
    </li>
    <li>
        <a href="{{ path('documento_edit', { 'id': entity.id }) }}">
            Edit
        </a>
    </li>
   
</ul>

src/Area4/ContableBundle/Resources/views/Documento/tableIndex.html.twig
<table class="general" style="text-align: center;">
    <tr class="txt_adorno">
        <th>Tipo</th>
        <th>Numero</th>
        <th>Fecha</th>
        <th>Estado</th>
        <th>Total</th>
        <th>Acción</th>
    </tr>
{% for doc in entities %}
    <tr>
        <td>{{ doc.tipo }}</td>
        <td>{{ doc.numero }}</td>
        <td>{% if doc.fecha %}{{ doc.fecha|date('d-m-Y') }}{% endif%}</td>
        <td>{{doc.getEstadotoString}}</td>
        <td>${{ doc.total }}</td>
        <td style="text-align: center;">
            <a href="javascript:editDocumento('{{path('documento_edit', {'id':doc.id})}}')">
                <img src="{{asset('img/icons/newspaper-edit.png')}}" alt="Modificar" title="Modificar documento"/>
            </a>
        </td>
    </tr>
{% endfor %}
</table>